# LAPTOP SPECIFIC CONFIG — Template
# ----------------------
# Run `hyprctl monitors all` to find your precise monitor name and resolution
# and replace the auto-detect line below.

# Source the dynamic touchpad state (Laptop only)
source = ~/.config/hypr/touchpad.conf

# 1. Input: Hardware Quirks
input {
    touchpad {
        natural_scroll = true
        tap-to-click = true
        drag_lock = true
        disable_while_typing = true
    }

    accel_profile = adaptive
    sensitivity = 0.5
}

# 3. Laptop Keybinds
bind = $mainMod, M, exec, ~/.config/hypr/scripts/mirror-hotplug.sh
bindel = ,XF86MonBrightnessUp, exec, ~/.config/swaync/scripts/brightness.sh up
bindel = ,XF86MonBrightnessDown, exec, ~/.config/swaync/scripts/brightness.sh down