# Machine Identity — Laptop Template
# Copy this file to your profile folder and customize it.
HOST_TYPE="laptop"
HOST_NAME="my-laptop"         # Give your machine a name
DISTRO="arch"                 # arch, garuda, cachyos, endeavour, etc.
HAS_BATTERY=true
HAS_BACKLIGHT=true
HAS_TOUCHPAD=true

# Initial Waybar Settings
WAYBAR_LAYOUT="2-Topbar-Detailed"
WAYBAR_STYLE="5-Glass-Pill"

# Interactive Hardware Identity
KB_LAYOUT="us"
KB_VARIANT=""
