# -----------------------------------------------------
# AUTOSTART & SERVICES
# -----------------------------------------------------

# --- CORE SERVICES ---
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = /usr/lib/polkit-kde-authentication-agent-1
exec-once = /usr/lib/pam_kwallet_init
exec-once = swaync
exec-once = hypridle
exec-once = hyprsunset
exec-once = kbuildsycoca6

# --- CLIPBOARD & SCRIPTS ---
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
exec-once = ~/.config/hypr/scripts/xhost-root.sh
exec-once = ~/.config/wallpapers/mpvpaper-pool.sh
exec-once = killall waybar; waybar

# --- APPS & TRAY ---
exec-once = easyeffects --service-mode -w &
exec-once = steam -silent &
exec-once = heroic --no-gui &
exec-once = sleep 2 && blueman-applet &
exec-once = [workspace special:standard silent] protonvpn-app

# Audio Wake Hack
exec-once = sh -c "pavucontrol & sleep 2; killall pavucontrol" &
exec-once = sleep 4 && wpctl status > /dev/null && wpctl set-mute @DEFAULT_AUDIO_SOURCE@ 0