# -----------------------------------------------------
# AUTOSTART & SERVICES
# -----------------------------------------------------

# --- CORE SERVICES ---
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = /usr/lib/polkit-kde-authentication-agent-1
#exec-once = /usr/lib/pam_kwallet_init -- ts is for using KDE Plasma Only
exec-once = /usr/bin/gnome-keyring-daemon --start --components=secrets # for Hyprland setup
exec-once = swaync
exec-once = hypridle
exec-once = hyprsunset
exec-once = kbuildsycoca6 --noincremental
exec-once = sleep 1 && gdbus call --session --dest=org.kde.kded6 --object-path /kded --method org.kde.kded6.loadModule statusnotifierwatcher

# --- CLIPBOARD & SCRIPTS ---
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
exec-once = ~/.config/hypr/scripts/xhost-root.sh
exec-once = ~/.config/hypr/scripts/wallpaper-selector.sh --init
exec-once = killall waybar; waybar

# Note: Personalized Apps and Trays should be placed in your host-specific 
# override file (e.g. hosts/your-host/hypr-host.conf) so they don't break 
# other users' setups!