$color0 = rgb(141513)
$color1 = rgb(88DD77)
$color2 = rgb(A964AE)
$color3 = rgb(8C9289)
$color4 = rgb(9FAC9B)
$color5 = rgb(ACD7A5)
$color6 = rgb(CFBDCE)
$color7 = rgb(e1eae0)
$color8 = rgb(9da39c)
$color9 = rgb(88DD77)
$color10 = rgb(A964AE)
$color11 = rgb(8C9289)
$color12 = rgb(9FAC9B)
$color13 = rgb(ACD7A5)
$color14 = rgb(CFBDCE)
$color15 = rgb(e1eae0)
$background = rgb(141513)
$foreground = rgb(e1eae0)
$cursor = rgb(e1eae0)
