# -----------------------------------------------------
# INPUT DEVICES (Fallback Kit)
# -----------------------------------------------------
# Note: Host-specific config will override these values.

input {
    # Keyboard layout
    kb_layout = us
    follow_mouse = 1
    sensitivity = 0 

    touchpad {
        natural_scroll = true
    }
}

#gesture {
#    workspace_swipe = true
#}

gesture = 3, horizontal, workspace

device {
    name = epic-mouse-v1
    sensitivity = -0.5
}