# -----------------------------------------------------
# WINDOW RULES
# -----------------------------------------------------

# --- GAME RULES (Tearing Enabled) ---
 #windowrule = immediate 1, match:class ^(payday2_win32_release.exe)$
 #windowrule = immediate 1, match:class ^(steam_app_\d+)$
 #windowrule = immediate 1, match:class ^(Terraria.exe)$
 #windowrule = immediate 1, match:class ^(gamescope)$

# --- WORKSPACE RULES ---
# Smart gaps (No gaps when only 1 window)
workspace = w[tv1], gapsout:0, gapsin:0, border:0, rounding:0
workspace = f[1], gapsout:0, gapsin:0, border:0, rounding:0

# --- SPECIAL APPS AUTOMATION ---
# Force ProtonVPN to behave if it ignores the silent launch
# windowrule = workspace special:niche silent, match:class ^(ProtonVPN)$

# Auto-Route Apps (Optional Examples)
# windowrulev2 = workspace special:work, class:^(code-url-handler)$
# windowrulev2 = workspace special:hobby, class:^(Spotify)$