#!/bin/bash
# ==============================================================================
# MODULE: 01-stow-configs.sh
# Purpose: Dynamically creates target directories, stows dotfiles safely,
#          and bootstraps first-run requirements (pywal, touchpad, shell.local).
# ==============================================================================

source "$INSTALLER_DIR/scripts/utils.sh"

# Source profile metadata if available
if [[ -f "$DOTFILES_DIR/hosts/$TARGET/profile.conf" ]]; then
    source "$DOTFILES_DIR/hosts/$TARGET/profile.conf"
fi

print_step "Stowing configurations..."

# 1. Link Home Files (No --adopt, safer)
print_step ">> Stowing Home Directory Files..."
cd "$DOTFILES_DIR" || exit 1
stow -v -R -t "$HOME" home

# 2. Dynamic Target Creation for Core
# This prevents GNU Stow from "folding" an entire directory if the target 
# doesn't exist, which causes conflicts later. We create every top-level 
# directory found in core/ inside ~/.config first.
print_step ">> Preparing ~/.config for Core Apps..."
find "$DOTFILES_DIR/core" -mindepth 1 -maxdepth 1 -type d -exec basename {} \; | while read -r dir; do
    mkdir -p "$HOME/.config/$dir"
done

print_step ">> Stowing Core Configs..."
stow -v -R -t "$HOME/.config" core

# 3. Handle Host-Specific Config Overrides
print_step ">> Applying Host-Specific Overrides for $TARGET..."
safe_link "$DOTFILES_DIR/hosts/$TARGET/.config/swaync/config.json" "$HOME/.config/swaync/config.json"

# 4. Link Hyprland Environment
print_step ">> Stowing Hyprland Environment..."
stow -v -R -t "$HOME/.config/hypr" hyprland
safe_link "$DOTFILES_DIR/hosts/$TARGET/hypr-host.conf" "$HOME/.config/hypr/host.conf"
safe_link "$DOTFILES_DIR/hosts/$TARGET/kitty-host.conf" "$HOME/.config/kitty/host.conf"

# 5. Waybar Deployment
print_step ">> Initializing Waybar Protocol..."
check_fonts

# Dynamically link the starting layout and style based on the Host Profile metadata
if [[ -n "$WAYBAR_LAYOUT" && -f "$DOTFILES_DIR/core/waybar/layouts/${WAYBAR_LAYOUT}.jsonc" ]]; then
    safe_link "$DOTFILES_DIR/core/waybar/layouts/${WAYBAR_LAYOUT}.jsonc" "$HOME/.config/waybar/config.jsonc"
else
    # Fallback if profile metadata is incomplete
    safe_link "$DOTFILES_DIR/core/waybar/layouts/2-Topbar-Detailed.jsonc" "$HOME/.config/waybar/config.jsonc"
fi

if [[ -n "$WAYBAR_STYLE" && -f "$DOTFILES_DIR/core/waybar/styles/${WAYBAR_STYLE}.css" ]]; then
    safe_link "$DOTFILES_DIR/core/waybar/styles/${WAYBAR_STYLE}.css" "$HOME/.config/waybar/style.css"
else
    safe_link "$DOTFILES_DIR/core/waybar/styles/5-Glass-Pill.css" "$HOME/.config/waybar/style.css"
fi

# Fix script permissions
chmod +x "$DOTFILES_DIR/core/waybar/scripts/"*.sh
chmod +x "$DOTFILES_DIR/core/hypr/scripts/"*.sh
chmod +x "$DOTFILES_DIR/core/swaync/scripts/"*.sh

# 6. FIRST-RUN BOOTSTRAP — Touchpad State File
# The laptop hypr-host.conf sources touchpad.conf, which doesn't exist
# until the toggle script creates it. Create a sane default.
if [[ "$HAS_TOUCHPAD" == "true" ]]; then
    TOUCHPAD_CONF="$HOME/.config/hypr/touchpad.conf"
    if [[ ! -f "$TOUCHPAD_CONF" ]]; then
        print_step ">> Creating default touchpad state file..."
        echo "# Auto-generated by installer — touchpad enabled by default" > "$TOUCHPAD_CONF"
    fi
fi

print_step ">> Configuring Hardware Modules (Keyboard & Monitor)..."
cat > "$KB_CONF" << EOF
# Auto-generated by installer based on profile.conf
input {
    kb_layout = ${KB_LAYOUT:-us}
    kb_variant = ${KB_VARIANT:-}
}
EOF

# --- 7.1 MONITOR CONFIG ---
cat > "$HOME/.config/hypr/modules/monitor.conf" << EOF
# DYNAMIC MONITOR CONFIG
# Generated based on your hardware profile
monitor = ${MONITOR_NAME:-},preferred,auto,${SCALE:-1.0}
EOF


# 8. FIRST-RUN BOOTSTRAP — Pywal Color Generation
# Rofi themes, Kitty, and Hyprland all import colors from ~/.cache/wal/
# which only exists after pywal runs at least once. Bootstrap it now.
DEFAULT_WALL="$DOTFILES_DIR/core/wallpapers/library/Jack-Cooper-BT-7274.jpg"

if [[ ! -f "$HOME/.cache/wal/colors-hyprland.conf" ]] && command -v wal &>/dev/null; then
    print_step ">> Bootstrapping Pywal color scheme..."
    if [[ -f "$DEFAULT_WALL" ]]; then
        wal -q -n -i "$DEFAULT_WALL"
        # Copy the generated Hyprland color variables
        if [[ -f "$HOME/.cache/wal/colors-hyprland.conf" ]]; then
            cp "$HOME/.cache/wal/colors-hyprland.conf" "$HOME/.config/hypr/modules/colors.conf"
        fi
        
        # Save explicit wallpaper state so init doesn't guess
        mkdir -p "$HOME/.config/wallpapers"
        echo "$DEFAULT_WALL" > "$HOME/.config/wallpapers/.current_wallpaper"
        rm -f "$HOME/.config/wallpapers/.current_effect_image"
        
        print_success "Pywal bootstrapped with default wallpaper."
    else
        print_warning "Default wallpaper not found. Pywal colors will be generated on first wallpaper selection."
    fi
else
    # Safeguard: Even if colors exist, ensure the state file exists for a fresh clone
    if [[ ! -f "$HOME/.config/wallpapers/.current_wallpaper" ]]; then
        mkdir -p "$HOME/.config/wallpapers"
        echo "$DEFAULT_WALL" > "$HOME/.config/wallpapers/.current_wallpaper"
    fi
    print_success "Pywal cache already exists. Skipping bootstrap."
fi

# 8. USER KEYBINDS — Link host user-keybinds.conf
USER_BINDS="$DOTFILES_DIR/hosts/$TARGET/user-keybinds.conf"
if [[ -f "$USER_BINDS" ]]; then
    print_step ">> Linking user keybinds for $TARGET..."
    safe_link "$USER_BINDS" "$HOME/.config/hypr/user-keybinds.conf"
fi

# 9. SHELL PERSONALIZATION — Link host shell.local
SHELL_LOCAL="$DOTFILES_DIR/hosts/$TARGET/shell.local"
if [[ -f "$SHELL_LOCAL" ]]; then
    print_step ">> Linking shell personalization for $TARGET..."
    safe_link "$SHELL_LOCAL" "$HOME/.zshrc.local"
fi

# 9. Live Interface Reload
if pgrep Hyprland > /dev/null; then
    print_step ">> Reloading Hyprland interface elements..."
    hyprctl reload &> /dev/null
    
    # Force Kill & Restart Waybar
    pkill waybar || true
    waybar -c "$HOME/.config/waybar/config.jsonc" -s "$HOME/.config/waybar/style.css" &> /dev/null &
    
    # Reload SwayNC
    if command -v swaync-client &> /dev/null; then
        swaync-client -rs &> /dev/null
    fi
fi

print_success "Configs Stowed Successfully."
