# LAPTOP SPECIFIC CONFIG
# ----------------------

# 1. Monitor: Auto-detect (Plug and Play)
monitor=eDP-1,1920x1200@60.0,0x0,1.0

# 2. Input: Enable Trackpad Gestures
input {
    kb_layout = us
    follow_mouse = 1
    touchpad {
        natural_scroll = true
        
        # This helps ignore the 'electrical jitter' from the charger
        tap-to-click = true
        drag_lock = true
        
        # Ensures your movement is 1:1 with the sensor
        disable_while_typing = true
        
    }

    # This is the most important setting for charger lag
    accel_profile = adaptive
    
    # Increase this until the trackpad feels 'light' enough for you
    # Try 0.3, then 0.5 if it still feels heavy
    sensitivity = 0.5
}

# 3. Laptop Keybinds
# Mirror Screen Script (Only useful on laptop)
bind = SUPER, M, exec, ~/.config/hypr/scripts/mirror-hotplug.sh

# Brightness Controls (Only useful on laptop)
bindel = ,XF86MonBrightnessUp, exec, ~/.config/swaync/scripts/brightness.sh up
bindel = ,XF86MonBrightnessDown, exec, ~/.config/swaync/scripts/brightness.sh down

# Lid Switch (Lock when closed)
bindl = , switch:on:Lid Switch, exec, hyprlock