# LAPTOP SPECIFIC CONFIG
# ----------------------

# 1. Monitor: Auto-detect (Plug and Play)
 monitor=eDP-1,1920x1200@60.0,0x0,1.5,bitdepth,10, vrr, 1

# 2. Input: Enable Trackpad Gestures
input {
    kb_layout = us
    follow_mouse = 1
    touchpad {
        natural_scroll = true
    }
}

# 3. Laptop Keybinds
# Mirror Screen Script (Only useful on laptop)
bind = SUPER, M, exec, ~/.config/hypr/scripts/mirror-hotplug.sh

# Brightness Controls (Only useful on laptop)
bindel = ,XF86MonBrightnessUp, exec, ~/.config/swaync/scripts/brightness.sh up
bindel = ,XF86MonBrightnessDown, exec, ~/.config/swaync/scripts/brightness.sh down

# Lid Switch (Lock when closed)
bindl = , switch:on:Lid Switch, exec, hyprlock