# DESKTOP SPECIFIC CONFIG
# -----------------------

# 1. Monitor: Define your specific desktop screens here
# monitor = DP-1, preferred, auto, 1
# monitor = HDMI-A-1, 1920x1080@60, 2560x0, 1

# 2. Input: Mouse settings (No natural scroll)
input {
    kb_layout = us
    follow_mouse = 1
    touchpad {
        natural_scroll = false
    }
}

# Custom Desktop Peripherals
device {
    name = epic-mouse-v1
    sensitivity = -0.5
}

# 3. Desktop Keybinds
# (Add any macro keys or specific desktop tools here)