# Machine Identity — Desktop Template
# Copy this file to your profile folder and customize it.
HOST_TYPE="desktop"
HOST_NAME="my-desktop"        # Give your machine a name
DISTRO="arch"                 # arch, garuda, cachyos, endeavour, etc.
HAS_BATTERY=false
HAS_BACKLIGHT=false
HAS_TOUCHPAD=false

# Initial Waybar Settings
WAYBAR_LAYOUT="2-Topbar-Detailed"
WAYBAR_STYLE="5-Glass-Pill"

# Interactive Hardware Identity
KB_LAYOUT="us"
KB_VARIANT=""

# DISPLAY & SCALING (Detected during installation)
MONITOR_NAME="auto"
SCALE="1.0"
