# TITANFALL 2 STARSHIP THEME
# --------------------------

format = """
[░▒▓](#00e0ff)\
[  ](bg:#00e0ff fg:#090a0a)\
[](bg:#1a1b1d fg:#00e0ff)\
$directory\
[](fg:#1a1b1d bg:#2b2c2f)\
$git_branch\
$git_status\
[](fg:#2b2c2f bg:#1a1b1d)\
$nodejs\
$rust\
$golang\
$php\
[](fg:#1a1b1d)\
\n$character"""

[directory]
style = "bg:#1a1b1d fg:#00e0ff"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:#2b2c2f"
format = "[[ $symbol $branch ](fg:#00e0ff bg:#2b2c2f)]($style)"

[git_status]
style = "bg:#2b2c2f"
format = "[[($all_status$ahead_behind )](fg:#00e0ff bg:#2b2c2f)]($style)"

[nodejs]
symbol = ""
style = "bg:#1a1b1d"
format = "[[ $symbol ($version) ](fg:#769ff0 bg:#1a1b1d)]($style)"

[rust]
symbol = ""
style = "bg:#1a1b1d"
format = "[[ $symbol ($version) ](fg:#769ff0 bg:#1a1b1d)]($style)"

[golang]
symbol = "ﳑ"
style = "bg:#1a1b1d"
format = "[[ $symbol ($version) ](fg:#769ff0 bg:#1a1b1d)]($style)"

[php]
symbol = ""
style = "bg:#1a1b1d"
format = "[[ $symbol ($version) ](fg:#769ff0 bg:#1a1b1d)]($style)"

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#1d2230"
format = "[[  $time ](fg:#a0a9cb bg:#1d2230)]($style)"

[character]
success_symbol = "[➜](bold #00ff99)"
error_symbol = "[✗](bold #ff3b3b)"