# TITANFALL KITTY THEME
# ---------------------

# 1. Fonts (JetBrains Mono is recommended for the icons)
font_family      ShureTechMono Nerd Font
italic_font      auto
bold_italic_font auto

# (Optional: Adjust line height if it feels too cramped)
modify_font cell_height 110%

# 2. Window Layout
window_padding_width 10
hide_window_decorations yes
confirm_os_window_close 0

# 3. Colors (Pywal Integrated)
include ~/.cache/wal/colors-kitty.conf

# 4. Host Specific Settings (Font Size)
# This file doesn't exist yet! The install script creates it.
include host.conf