# -----------------------------------------------------
# TITANFALL HYPRLAND MASTER CONFIG
# -----------------------------------------------------

# 1. GLOBAL VARIABLES (Must be defined first)
$mainMod = SUPER
$terminal = kitty
$fileManager = dolphin
$menu   = rofi -show drun -terminal kitty -theme ~/.config/rofi/themes/launcher.rasi
$runner = rofi -show run  -terminal kitty -theme ~/.config/rofi/themes/runner.rasi

# 2. DEFAULT MONITOR (Agnostic Fallback)
monitor=,preferred,auto,auto

# 3. ENVIRONMENT VARIABLES
env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24
env = GDK_BACKEND,wayland,x11,*
env = QT_QPA_PLATFORM,wayland;xcb
env = SDL_VIDEODRIVER,wayland
env = CLUTTER_BACKEND,wayland
env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_TYPE,wayland
env = XDG_SESSION_DESKTOP,Hyprland
env = XDG_MENU_PREFIX,arch- 

# 4. SOURCE MODULES (Load the components)
source = ~/.config/hypr/modules/autostart.conf
source = ~/.config/hypr/modules/visuals.conf
source = ~/.config/hypr/modules/input.conf
source = ~/.config/hypr/modules/windowrules.conf
source = ~/.config/hypr/modules/keybinds.conf

# 5. HOST SPECIFIC OVERRIDES (Last to override defaults)
source = ~/.config/hypr/host.conf